import { parseLinkedInChat } from "../utils/chatParser.js";
import initContent from "./initContent.jsx";
import init from "./initContent.jsx";
import { mainGPTcall, summarizeLearnings } from "./openai.js";
import showModal from "../utils/showModal.js";
import updateChatInput from "../utils/updateChatInput.js";
import { PROFILE_MEMORY_KEY } from "../utils/constants";
import gatherInitialInfo from "./gatherInitialInfo.jsx";
import triggerMessage from "../utils/triggerMessage.js";
import handleMessages from "./handleMessages.js";

// Listen for messages from background script
chrome.runtime.onMessage.addListener(async (request, sender, sendResponse) => {
  if (request.type === "PARSE_CHAT") {
    const messages = parseLinkedInChat();

    init();
    await gatherInitialInfo();

    // Testing
    // updateChatInput("New test message to recruiter generated by AI");
    // triggerMessage();

    handleMessages(messages, sendResponse);
  }

  if (request.type === "READ_STORAGE") {
    const value = localStorage.getItem(request.data);
    sendResponse({ value });
  }

  if (request.type === "UPDATE_STORAGE") {
    Object.entries(request.data).forEach(([key, value]) => {
      localStorage.setItem(key, value);
    });
  }

  return true;
});

// Initialize React on page
initContent();
